### ISSUE TITLE
Rails group project - Recipe app

### ISSUE THREAD

**Issue by paulinagonzalezc** [paulinagonzalezc/recipe-app-rails#12]
Rails group project - Recipe app
Link to repo: https://github.com/users/paulinagonzalezc/projects/1/views/1

Hello, we are a team of 2:
Team member 1: @paulinagonzalezc
Team member 2: @momotsow

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @paulinagonzalezc and @momotsow,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly provide the link to the Kanban instead of your repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @paulinagonzalezc and @momotsow,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### I am presented with a 404 error page when I visit your link. Perhaps your repo is set to private?

![image](https://user-images.githubusercontent.com/36542986/225030260-14654b03-c450-48a5-a9ba-6d86d46776e9.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by PinkMoon25** [comment]
Hi @paulinagonzalezc & @momotsow , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/BDGZ5LdDUkHCS8kS8R/giphy.gif"/>

## Highlights
Kanban Board setup :heavy_check_mark: 
Distributed in a fair way :heavy_check_mark: 
All cards assigned :heavy_check_mark: 
Each requirements have corresponding card :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
